blog/blog/urls.py
from django.conf.urls import url,include,patterns
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^sblog/',include('sblog.urls')),
]

blog/sblog/urls.py
from django.conf.urls import *
 
urlpatterns = patterns(('sblog.views'),
    url(r'^bloglist/$', 'blog_list', name='blog_list'),
    url(r"^$",'home' , name ='home'),
    url(r'^blog/(?P<_id>\d+)/$', 'blog_show', name='blog_show'),
    url(r'^add/$', 'blog_add', name='blog_add'),
    url(r'^del/(?P<_id>\w+)/$', 'blog_del', name='blog_del'),
    url(r'^edit/(?P<_id>\w+)/$', 'blog_edit', name='blog_edit'),
    # name属性是给这个url起个别名，可以在模版中引用而不用担心urls文件中url的修改 引用方式为{% url bloglist %}
)

blog/sblog/models.py
from django.db import models

# Create your models here.
class Tag(models.Model):
    """docstring for Tags"""
    tag_name = models.CharField(max_length=20, blank=True)
    create_time = models.DateTimeField(auto_now_add=True)
 
    def __str__(self):
        return self.tag_name
 
class Author(models.Model):
    """docstring for Author"""
    name = models.CharField(max_length=30)
    email = models.EmailField(blank=True)
    website = models.URLField(blank=True)
 
    def __str__(self):
        return u'%s' % (self.name)
 
class Blog(models.Model):
    """docstring for Blogs"""
    caption = models.CharField(max_length=50)
    author = models.ForeignKey(Author)
    tags = models.ManyToManyField(Tag, blank=True)
    content = models.TextField()
    publish_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)
    class Meta:
            ordering = ['-caption']
 
    def __str__(self):
        return u'%s %s %s' % (self.caption, self.author, self.publish_time)

blog/sblog/forms.py
from django import forms
 
class BlogForm(forms.Form):
    caption = forms.CharField(label='title', max_length=100)
    content = forms.CharField(widget=forms.Textarea)

blog/sblog/views.py
from django.shortcuts import render,render_to_response
from sblog.models import Blog
from django.http import Http404
from django.http import HttpResponseRedirect
from django.template import RequestContext
from sblog.models import Author
from sblog.forms import BlogForm
# Create your views here.

def blog_del(request, _id):
    try:
        blog = Blog.objects.get(id=_id)
    except Exception:
    	return render(request, "base.html")
    if blog:
        blog.delete()
        return HttpResponseRedirect("/sblog/bloglist/")
    blogs = Blog.objects.all()
    return render_to_response("blog_list.html", {"blogs": blogs})

def blog_edit(request, _id):
    if request.method == 'POST':
        form = BlogForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            title = cd['caption']
            author = Author.objects.get(id=1)
            content = cd['content']
            blog = Blog.objects.get(id=_id)
            blog.caption = title
            blog.content = content
            blog.save()
            return HttpResponseRedirect('/sblog/blog/%s' % _id)
    else:
        try:
            blog = Blog.objects.get(id=_id)
        except Exception:
            return render(request, "base.html")
        form = BlogForm(initial={'caption': blog.caption, 'content': blog.content}, auto_id=False)
        return render_to_response('blog_add.html',{'blog': blog, 'form': form, 'id': _id},context_instance=RequestContext(request))

def blog_add(request):
    if request.method == 'POST':
        form = BlogForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            title = cd['caption']
            author = Author.objects.get(id=1)
            content = cd['content']
            blog = Blog(caption=title, author=author, content=content)
            blog.save()
            id = Blog.objects.order_by('-publish_time')[0].id
            return HttpResponseRedirect('/sblog/blog/%s' % id)
    else:
        form = BlogForm()
    return render_to_response('blog_add.html',{'form': form}, context_instance=RequestContext(request))

def home(request):
    return render(request, "home.html")

def blog_list(request):
    blogs =list( Blog.objects.all())
    return render_to_response("blog_list.html", {"blogs": blogs})

def blog_show(request, _id):
    try:
        blog = Blog.objects.get(id=_id)
    except Blog.DoesNotExist:
        return render(request, "base.html")
    return render_to_response("blog_show.html", {"blog": blog})
        

blog/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <title>
        {% block title %}{% endblock %}        
    </title>
</head>
{% load static from staticfiles %}
{% static 'sblog/img/jj_ta.jpg' as myphoto %}
 <style type="text/css">
       body 
       {
            background-image: url({{myphoto}});
            background-repeat:no-repeat;
        }
    </style>
<body>
    <h1>  
        Lnever &nbsp;&nbsp;&nbsp;
        <a href="{% url 'home' %}" style="font-size:26px">       [   Home  ]</a> &nbsp;&nbsp;                      
        <a href="{% url 'blog_list' %} "style="font-size:26px">   [  Articles ] </a>&nbsp;&nbsp;
        <a href="{% url 'blog_add' %} "style="font-size:26px">   [  New ]</a>                                        
    </h1>
    <div> 
        
        <p  style="text-align:right;">
            <a href="https://docs.djangoproject.com/en/1.9/">  << powered by django. </a>
        </p>
    </div>
    {% block content %}
    {% endblock %}
    {% block footer %}
    {# 任何每个页面都可能修改的文本区域的页脚 #}
        
    {% endblock %}
    <div>
        
    </div>
</body>
</html>

blog/templates/sblog/blog_add.html
{% extends "base.html" %}
 
{% block title %} New Article {% endblock %}   
 
{% block content %} 
 
<form action="" method="post">
    {% csrf_token %} 
    <div class="field">
        <p><label for="id_caption">Title :  </label></p>
        {% if form.caption.errors %}
        <div class="alert alert-error">
            {{ form.caption.errors }}          
        </div>
        {% endif %}
        {{ form.caption }}
    </div>
    <br>
    <br>
    <div class="field">        
        <p><label for="id_content">Content: </label></p>
        {% if form.content.errors %}
        <div class="alert alert-error">
            {{ form.content.errors }}
        </div>
        {% endif %}
        {{ form.content }}
    </div>
    <br><br>
    <div class="form-actions" align="left">
        <input class="btn btn-primary" type="submit" value="Save">
    </div>
</form>
{% endblock %}

blog/templates/sblog/blog_list.html
{%extends "base.html" %}
 
{% block title %} Article List {% endblock %}
 
{% block content %}
<div class="content">
<h5>-------------------------------------------------------------------------------------------<h5>
    {% for blog in blogs %}

        <h3> <a href="{% url 'blog_show' blog.id%}">{{blog.caption}} </a>  </h3>
        <h5>-------------------------------------------------------------------------------------------<h5>
    {% endfor %}    
</div>    
{% endblock %}

blog/templates/sblog/blog_show.html
{%extends "base.html" %}
 
{% block title %} {{ blog.caption }} {% endblock %}
 
{% block content %}
<div class="content">
    <h2>#{{ blog.caption }}</h2>
    
<h5>-------------------------------------------------------------------------------------------<h5>
<br>
    <div>{{ blog.content }} </div>
</div>    
<br><br>
<h5>-------------------------------------------------------------------------------------------<h5>
<a href="{% url 'blog_edit' blog.id%}"><input type="button" value="Edit"> </a>
<a href="{% url 'blog_del' blog.id%}"><input type="button" value="Delete"> </a>
{% endblock %}

blog/templates/sblog/home.html
{%extends "base.html" %}
 
{% block title %} Lnever Home {% endblock %}
 
{% block content %}
<h3> Welcome to Lnever's Home </h3>  
{% endblock %}